### ISSUE TITLE
/planas POST error code 401

### ISSUE THREAD

**Issue by Suratorius** [Benas3000/MaistoApi#1]
Atlikus unit testavima paaiškėjo, kad meginant postinti duomenis /planas adresu įvyksta klaida.

    def test_PlanasAddToDB(test_client, init_database):

        response = test_client.post('/planas',
                                    data=json.dumps(dict(pavadinimas='patkennedy79@hotmail.com',
                                              Komentaras='FlaskIsGreat',
                                              ivertinimas=1)), content_type='application/json')
    
>       assert response.status_code == 201
E       assert 401 == 201
E         -401
E         +201

**Comment by Benas3000** [comment]
Klaida pataisyta

**Comment by Benas3000** [comment]
Užbaigta taisyti pilanai
